In [1]:
import pandas as pd

In [9]:
dataset = pd.read_excel("Week7_Store_Data_Sample.xlsx")
dataset

,Order ID,Order Date,Customer ID,Segment,Region,Category,Product Name,Price,Quantity,Discount,Sales
0,CA-2016-152156,2016-11-08,EB-13930,Хувь хүн,Баянзүрх,"Чихэр, печенье",Shokolinsen 250 гр,3300,2,0.00,6600.0
1,CA-2016-152156,2016-11-08,EB-13930,Хувь хүн,Баянзүрх,"OO ийн цаас, сальфетка",Хэрэглээ 00ийн цаас,500,3,0.00,1500.0
2,CA-2016-138688,2016-06-12,MO-17950,Байгууллага,Хан-Уул,"Чихэр, печенье",Алимтай жигнэмэг 230 гр,3100,2,0.00,6200.0
3,US-2015-108966,2015-10-11,JO-15550,Хувь хүн,Баянзүрх,Хиам бууз,Золотой янта 500 гр,2800,5,0.00,14000.0
4,US-2015-108966,2015-10-11,JO-15550,Хувь хүн,Баянзүрх,Ундаа ус,Punch 450 мл,1150,2,0.00,2300.0
...,...,...,...,...,...,...,...,...,...,...,...
95,US-2017-109484,2017-11-06,JR-15700,Гишүүн,Хан-Уул,"Компот варенье, хүүхдийн тэжээл",Hainich нухаш,3300,1,0.03,3201.0
96,CA-2017-161018,2017-11-09,AJ-10945,Гишүүн,Сүхбаатар,Самар чипс,Lays чипс 80 гр,2300,7,0.03,15617.0
97,CA-2017-157833,2017-06-17,BM-11575,Хувь хүн,Хан-Уул,"Набор, шоколад, бохь",Монстров 23 гр,500,3,0.00,1500.0
98,CA-2016-149223,2016-09-06,CV-12805,Байгууллага,Чингэлтэй,Архи пиво,Арвай 0.100,2000,6,0.00,12000.0
99,CA-2016-158568,2016-08-29,DK-12835,Гишүүн,Чингэлтэй,Бэлэн гоймон,Тэйсти гоймон 110 гр,1800,7,0.03,12222.0

In [13]:
order_id = dataset['Order ID'].values
order_date = dataset['Order Date'].values
customer_id = dataset['Customer ID'].values
segment = dataset['Segment'].values
region = dataset['Region'].values
category = dataset['Category'].values
product_name = dataset['Product Name'].values
price = dataset['Price'].values
quantity = dataset['Quantity'].values
discount = dataset['Discount'].values
sales = dataset['Sales'].values

order_id_series = pd.Series(order_id)
order_date_series = pd.Series(order_date)
customer_id_series = pd.Series(customer_id)
segment_series = pd.Series(segment)
region_series = pd.Series(region)
category_series = pd.Series(category)
product_name_series = pd.Series(product_name)
price_series = pd.Series(price)
quantity_series = pd.Series(quantity)
discount_series = pd.Series(discount)
sales_series =pd.Series(sales)

# data = {
#     'Order ID'
# }

dataset1 = pd.DataFrame({'Order ID': order_id_series, 'Order Date': order_date_series, 'Customer ID': customer_id, 'Segment':segment, 'Region':region, 'Category': category, 'Product Name', 'Price', 'Quantity', 'Discount'})

0     CA-2016-152156
1     CA-2016-152156
2     CA-2016-138688
3     US-2015-108966
4     US-2015-108966
           ...
95    US-2017-109484
96    CA-2017-161018
97    CA-2017-157833
98    CA-2016-149223
99    CA-2016-158568
Length: 100, dtype: object